config/routes.rb
CatData::Application.routes.draw do
  resources :data

  get "home/index"

  get "home/crawl"

     resources :data

  root :to => 'home#index'

end

app/models/datum.rb
class Datum < ActiveRecord::Base
  attr_accessible :description, :format, :size, :title, :url, :value
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/data_controller.rb
class DataController < ApplicationController
  # GET /data
  # GET /data.json
  def index
    @data = Datum.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @data }
    end
  end

  # GET /data/1
  # GET /data/1.json
  def show
    @datum = Datum.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @datum }
    end
  end

  # GET /data/new
  # GET /data/new.json
  def new
    @datum = Datum.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @datum }
    end
  end

  # GET /data/1/edit
  def edit
    @datum = Datum.find(params[:id])
  end

  # POST /data
  # POST /data.json
  def create
    @datum = Datum.new(params[:datum])

    respond_to do |format|
      if @datum.save
        format.html { redirect_to @datum, notice: 'Datum was successfully created.' }
        format.json { render json: @datum, status: :created, location: @datum }
      else
        format.html { render action: "new" }
        format.json { render json: @datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /data/1
  # PUT /data/1.json
  def update
    @datum = Datum.find(params[:id])

    respond_to do |format|
      if @datum.update_attributes(params[:datum])
        format.html { redirect_to @datum, notice: 'Datum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data/1
  # DELETE /data/1.json
  def destroy
    @datum = Datum.find(params[:id])
    @datum.destroy

    respond_to do |format|
      format.html { redirect_to data_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def crawl
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def links
    doc = Nokogiri::HTML(open('http://www.google.com/search?q=data%20sets'))
    doc.css('div cite')
  end
end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/home_helper.rb
module HomeHelper

require 'rubygems'
require 'google/api_client'

def hunt
  client = Google::APIClient.new
  client.authorization.client_id = '968529503802.apps.googleusercontent.com'
  client.authorization.client_secret = 'lpRuAzg4NLJvFCDGMCRPMxau'  
  search = client.discovered_api('customsearch')
  response = client.execute(
    search.cse.list, 'q' => 'tetration'
  )
  status, headers, body = response
  @hunt = "123"
end

end

app/views/data/_form.html.erb
<%= form_for(@datum) do |f| %>
  <% if @datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@datum.errors.count, "error") %> prohibited this datum from being saved:</h2>

      <ul>
      <% @datum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :format %><br />
    <%= f.text_field :format %>
  </div>
  <div class="field">
    <%= f.label :size %><br />
    <%= f.text_field :size %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/data/edit.html.erb
<h1>Editing datum</h1>

<%= render 'form' %>

<%= link_to 'Show', @datum %> |
<%= link_to 'Back', data_path %>

app/views/data/index.html.erb
<h1>Listing data</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Url</th>
    <th>Value</th>
    <th>Format</th>
    <th>Size</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @data.each do |datum| %>
  <tr>
    <td><%= datum.title %></td>
    <td><%= datum.description %></td>
    <td><%= datum.url %></td>
    <td><%= datum.value %></td>
    <td><%= datum.format %></td>
    <td><%= datum.size %></td>
    <td><%= link_to 'Show', datum %></td>
    <td><%= link_to 'Edit', edit_datum_path(datum) %></td>
    <td><%= link_to 'Destroy', datum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Datum', new_datum_path %>

app/views/data/new.html.erb
<h1>New datum</h1>

<%= render 'form' %>

<%= link_to 'Back', data_path %>

app/views/data/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @datum.title %>
</p>

<p>
  <b>Description:</b>
  <%= @datum.description %>
</p>

<p>
  <b>Url:</b>
  <%= @datum.url %>
</p>

<p>
  <b>Value:</b>
  <%= @datum.value %>
</p>

<p>
  <b>Format:</b>
  <%= @datum.format %>
</p>

<p>
  <b>Size:</b>
  <%= @datum.size %>
</p>


<%= link_to 'Edit', edit_datum_path(@datum) %> |
<%= link_to 'Back', data_path %>

app/views/home/crawl.html.erb
<h1>Home#crawl</h1>
<hr>
<%= link_to "Index", home_index_path %>!

app/views/home/index.html.erb
<h1>Home#index</h1>

<%  links.each do |link|  %>
<%=   link.content      %> <br />
<%  end                   %>

<hr>

<%= link_to "Crawl", home_crawl_path %>!

<br />

<%= link_to "Data", data_path %>!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CatData</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>